In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("school.db")

In [25]:
students = pd.read_csv("students.csv")
students

       name   city  score
0   Youssef  Cairo     61
1      Omar   Alex     75
2      Nour   Giza     68
3     Salma  Cairo     94
4     Ahmed  Cairo     97
5      Mona  Luxor     62
6     Karim  Cairo     65
7     Laila   Giza     74
8      Sara  Aswan     98
9       Ali  Cairo     95
10     Hana   Giza     94
11    Tarek  Luxor     74
12     Dina  Luxor     97
13      Amr   Alex     60
14     Yara   Giza     87
15  Mostafa   Alex     77
16     Rana   Giza     73
17   Hassan   Alex     66
18     Nada  Cairo     84
19     Fady  Cairo     82
20   Mariam   Alex     98
21    Hazem   Alex     62
22    Rawan  Luxor     94
23   Sherif  Cairo     84
24   Farida  Cairo     95
25   Bassem   Alex     99
26      Aya   Alex     96
27     Wael   Giza     64
28     Heba  Cairo     74
29    Adham   Alex     65

In [26]:
students.to_sql("students", conn, if_exists="replace", index=False)

30

In [27]:
pd.read_sql_query("SELECT * FROM students", conn)

       name   city  score
0   Youssef  Cairo     61
1      Omar   Alex     75
2      Nour   Giza     68
3     Salma  Cairo     94
4     Ahmed  Cairo     97
5      Mona  Luxor     62
6     Karim  Cairo     65
7     Laila   Giza     74
8      Sara  Aswan     98
9       Ali  Cairo     95
10     Hana   Giza     94
11    Tarek  Luxor     74
12     Dina  Luxor     97
13      Amr   Alex     60
14     Yara   Giza     87
15  Mostafa   Alex     77
16     Rana   Giza     73
17   Hassan   Alex     66
18     Nada  Cairo     84
19     Fady  Cairo     82
20   Mariam   Alex     98
21    Hazem   Alex     62
22    Rawan  Luxor     94
23   Sherif  Cairo     84
24   Farida  Cairo     95
25   Bassem   Alex     99
26      Aya   Alex     96
27     Wael   Giza     64
28     Heba  Cairo     74
29    Adham   Alex     65

In [28]:
pd.read_sql_query("SELECT name, city, score FROM students", conn)

       name   city  score
0   Youssef  Cairo     61
1      Omar   Alex     75
2      Nour   Giza     68
3     Salma  Cairo     94
4     Ahmed  Cairo     97
5      Mona  Luxor     62
6     Karim  Cairo     65
7     Laila   Giza     74
8      Sara  Aswan     98
9       Ali  Cairo     95
10     Hana   Giza     94
11    Tarek  Luxor     74
12     Dina  Luxor     97
13      Amr   Alex     60
14     Yara   Giza     87
15  Mostafa   Alex     77
16     Rana   Giza     73
17   Hassan   Alex     66
18     Nada  Cairo     84
19     Fady  Cairo     82
20   Mariam   Alex     98
21    Hazem   Alex     62
22    Rawan  Luxor     94
23   Sherif  Cairo     84
24   Farida  Cairo     95
25   Bassem   Alex     99
26      Aya   Alex     96
27     Wael   Giza     64
28     Heba  Cairo     74
29    Adham   Alex     65

In [29]:
pd.read_sql_query("SELECT name, city, score FROM students WHERE city = 'Cairo'", conn)

      name   city  score
0  Youssef  Cairo     61
1    Salma  Cairo     94
2    Ahmed  Cairo     97
3    Karim  Cairo     65
4      Ali  Cairo     95
5     Nada  Cairo     84
6     Fady  Cairo     82
7   Sherif  Cairo     84
8   Farida  Cairo     95
9     Heba  Cairo     74

In [30]:
pd.read_sql_query("SELECT name  , score from students WHERE score >= 85",conn)

      name  score
0    Salma     94
1    Ahmed     97
2     Sara     98
3      Ali     95
4     Hana     94
5     Dina     97
6     Yara     87
7   Mariam     98
8    Rawan     94
9   Farida     95
10  Bassem     99
11     Aya     96

In [32]:
pd.read_sql_query("SELECT name , city , score from students WHERE city = 'Giza' AND score >= 80",conn)

   name  city  score
0  Hana  Giza     94
1  Yara  Giza     87

In [33]:
pd.read_sql_query("SELECT name, score FROM students ORDER BY score DESC", conn)

       name  score
0    Bassem     99
1      Sara     98
2    Mariam     98
3     Ahmed     97
4      Dina     97
5       Aya     96
6       Ali     95
7    Farida     95
8     Salma     94
9      Hana     94
10    Rawan     94
11     Yara     87
12     Nada     84
13   Sherif     84
14     Fady     82
15  Mostafa     77
16     Omar     75
17    Laila     74
18    Tarek     74
19     Heba     74
20     Rana     73
21     Nour     68
22   Hassan     66
23    Karim     65
24    Adham     65
25     Wael     64
26     Mona     62
27    Hazem     62
28  Youssef     61
29      Amr     60

In [34]:
pd.read_sql_query("SELECT name, score FROM students ORDER BY score DESC LIMIT 3", conn)

     name  score
0  Bassem     99
1    Sara     98
2  Mariam     98

In [36]:
pd.read_sql_query("SELECT name, score FROM students ORDER BY score DESC LIMIT 4 OFFSET 4", conn)

     name  score
0    Dina     97
1     Aya     96
2     Ali     95
3  Farida     95

In [37]:
pd.read_sql_query("SELECT name,city , score FROM students WHERE city = 'Cairo' ORDER BY score DESC LIMIT 3", conn)

     name   city  score
0   Ahmed  Cairo     97
1     Ali  Cairo     95
2  Farida  Cairo     95